"use client";

import { use, useEffect, useState } from "react";
import { InvoiceTemplate } from "@/components/billing/InvoiceTemplate";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

interface PageProps {
    params: Promise<{ id: string }>;
}

export default function InvoiceViewPage({ params }: PageProps) {
    // Ungroup params using use() hook for Next.js 15+ (or await if async component, but this is client)
    // Actually, in client components, params is a promise in recent Next.js versions, but let's handle safely.
    // For simplicity in this demo environment which might be Next 14 or 15:

    // safe unwind of params
    const resolvedParams = use(params);
    const invoiceId = resolvedParams.id;

    const [date, setDate] = useState<Date | null>(null);

    useEffect(() => {
        setDate(new Date());
    }, []);

    if (!date) return null; // Hydration mismatch prevention

    return (
        <div className="min-h-screen bg-gray-100 py-8 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto mb-6">
                <Link href="/">
                    <Button variant="outline" size="sm">
                        <ArrowLeft className="w-4 h-4 mr-2" /> Back to Generator
                    </Button>
                </Link>
            </div>

            <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-lg overflow-hidden min-h-[800px]">
                <InvoiceTemplate invoiceId={invoiceId} date={date} />
            </div>

            <div className="max-w-4xl mx-auto mt-8 text-center text-sm text-gray-500">
                <p>Generated by Bill Software UAE</p>
            </div>
        </div>
    );
}
